<div class="resume slide">																				
	<div class="page-content">
		<div class="entry">
			<p><strong><span class="titre-article">WeBatt est une petite société constituée de passionnés de la création Web.</span></strong></p>
			<p>Basée a Grassendorf dans le Bas-Rhin, elle vise a permettre a des particuliers, des associations ou des petites entreprises de la région d&rsquo;acquérir une visibilité sur internet. Son objectif est de fournir des sites web &laquo;&nbsp;clé en main&nbsp;&raquo; simples et esthétiques à prix raisonnable. </p>
		</div>
		<h2>Concept</h2>
	</div>
	<div class="page-content">
		<div class="entry">
			<p>
				<a class="gallery-item" href="http://vpevents.webatt.fr" target="_blank" rel="public/images/et_temp/vpevents-116754_388x222.jpg" >
					<img src="public/images/et_temp/vpevents-116754_59x59.jpg" alt="" />
				</a><br />
				<a class="gallery-item" href="http://galart.fr" target="_blank" rel="public/images/et_temp/galart-110929_388x222.jpg" >
					<img src="public/images/et_temp/galart-110929_59x59.jpg" alt="" />
				</a><br />
				<a class="gallery-item" href="http://li-ga.fr" target="_blank" rel="public/images/et_temp/liga-65144_388x222.jpg" >
					<img src="public/images/et_temp/liga-65144_59x59.jpg" alt="" />
				</a><br />
				<a class="gallery-item" href="http://tadja.fr" target="_blank" rel="public/images/et_temp/tadja-67531_388x222.jpg" >
					<img src="public/images/et_temp/tadja-67531_59x59.jpg" alt="" />
				</a><br />
				<a class="gallery-item" href="hhttp://thomasbatt.fr" target="_blank" rel="public/images/et_temp/thomasbatt-109550_388x222.jpg" >
					<img src="public/images/et_temp/thomasbatt-109550_59x59.jpg" alt="" />
				</a>
			</p>
		</div>
		<h2>Realisations</h2>
	</div>
	<div class="page-content">
		<div class="entry">
			<p><strong><span class="titre-article">A votre écoute, </span></strong><br />nous vous apporterons tout ce dont vous aurez besoin pour votre présence sur Internet avec des services contractuels à valeur ajoutée.</p>
			<ul>
			<li>Developement XHTML PHP</li>
			<li>Design Graphic</li>
			<li>Referencement</li>
			<li>Media sociaux</li>
			</ul>
			<p><br/></p>
		</div>
		<h2>Savoir-faire</h2>
	</div>
	<div class="page-content">
		<div class="entry">
			<p><strong><span class="titre-article">Un projet a nous soumettre?</span></strong></p>
			<p id="lien">N’hésitez pas à nous contacter par mail en remplissant le formulaire de <a href="#" rel="contact">contact</a> et nous vous répondrons le plus vite possible.</p>
		</div>
	<h2>Contact</h2>
	</div>
</div>