<div class="notre-concept slide">
	<div class="page-content">
		<div class="entry ">
			<p><strong><span class="titre-article">WeBatt est une petite société constituée de passionnés de la création Web.</span></strong></p>
			<p>Basée a Grassendorf dans le Bas-Rhin, elle vise a permettre a des particuliers, des associations ou des petites entreprises de la région d&rsquo;acquérir une visibilité sur internet. Son objectif est de fournir des sites web &laquo;&nbsp;clé en main&nbsp;&raquo; simples et esthétiques à prix raisonnable.</p>
			<p>&nbsp;</p>
			<p>Pour développer nos sites web, nous travaillons sur le concept automatisé de &laquo;&nbsp;Flux numérique&nbsp;&raquo; de différents services internet accessible par applications smartphone. Le résultat est qu&rsquo;il vous suffira de lancer sur votre téléphone différentes actions tel que: une écriture d&rsquo;article, une capture photo, une écoute musical ou un enregistrement vidéo, pour que les éléments correspondant soient instantanément visible sur votre site web.<br />
			Nos travaux sont tel une cartes de visite dynamique et de sauvegarde visuelle automatisée.<br />
			N’hésitez pas a nous contacter pour plus d&rsquo;informations sur les possibilités du concept.</p>
			<p>&nbsp;</p>
			<p>
				<a class="gallery-item" href="http://vpevents.webatt.fr" target="_blank" rel="public/images/et_temp/vpevents-116754_388x222.jpg" >
					<img src="public/images/et_temp/vpevents-116754_59x59.jpg" alt="" />
				</a><br />
				<a class="gallery-item" href="http://galart.fr" target="_blank" rel="public/images/et_temp/galart-110929_388x222.jpg" >
					<img src="public/images/et_temp/galart-110929_59x59.jpg" alt="" />
				</a><br />
				<a class="gallery-item" href="http://li-ga.fr" target="_blank" rel="public/images/et_temp/liga-65144_388x222.jpg" >
					<img src="public/images/et_temp/liga-65144_59x59.jpg" alt="" />
				</a><br />
				<a class="gallery-item" href="http://tadja.fr" target="_blank" rel="public/images/et_temp/tadja-67531_388x222.jpg" >
					<img src="public/images/et_temp/tadja-67531_59x59.jpg" alt="" />
				</a><br />
				<a class="gallery-item" href="hhttp://thomasbatt.fr" target="_blank" rel="public/images/et_temp/thomasbatt-109550_388x222.jpg" >
					<img src="public/images/et_temp/thomasbatt-109550_59x59.jpg" alt="" />
				</a>
			</p>
		</div>
		<h2>Concept</h2>
	</div>
</div>