<div id="wrapper">
	<div id="content">
		<div id="content-bg-bottom">
			<div id="header">
				<ul>
					<li class="active resume-nav"><a href="accueil" rel="resume">accueil</a></li>
					<li class="notre-concept-nav"><a href="concept" rel="notre-concept">Concept</a></li>
					<li class="contact-nav"><a href="contact" rel="contact">Contact</a></li>
				</ul>
				<br class="clear" />
				<div id="logo">
					<a href="#" rel="resume">
						<img src="public/images/logowebatt101.jpg" alt="WeBatt" class="logo"/>
					</a>
					<img class="overlay" src="public/images/photo-overlay.png" alt="" />
					<span>
						contact@webatt.fr
						<br/>
					</span>
				</div>
			</div>