<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8" />
		<title>WeBatt | Votre site web clé en main</title>
		<link rel="shortcut icon" href="public/images/faviconwebatt.png" />	
		<link rel="stylesheet" href="public/styles/style.css" type="text/css" media="screen" />
		<link rel='stylesheet' id='cntctfrm_stylesheet-css'  href='public/styles/style-contact.css' type='text/css' media='all' />

		<script type='text/javascript' src='public/scripts/jquery.min.js'></script>
		<script type="text/javascript" src="public/scripts/effects.js"></script>
	</head>

	<body class="blog gecko et_includes_sidebar">
		<?php require('apps/header.php'); ?>

		<?php require('apps/content.php'); ?>

		<?php require('apps/footer.php'); ?>
	</body>
</html>